import fsp from 'node:fs/promises';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { atomicWriteFile } from './util.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEFAULTS_DIR = path.resolve(__dirname, '..', 'defaults');

async function copyDefault(src: string, dest: string, force: boolean): Promise<boolean> {
  if (fs.existsSync(dest) && !force) return false;
  await fsp.mkdir(path.dirname(dest), { recursive: true });
  await fsp.copyFile(src, dest);
  return true;
}

const DEFAULT_CONFIG = `# theme-doctor.yaml — generated by \`theme-doctor init\`
version: 1

defaults:
  branch: main
  viewports: [375, 768, 1440]
  matrix:
    wp: ["latest"]
    wc: ["latest"]
    php: ["8.2"]
  sandbox: auto
  pr:
    create: true
    auto_merge_cosmetic: false
  budget:
    max_cost_usd_per_run: 5

# Register your WooCommerce themes below.
# Multiple source types are supported:
#
#   Local path:
#     - id: my-theme
#       source: { type: path, path: ../my-theme }
#       repo: myorg/my-theme        # optional — enables PR creation via gh
#       owner: "@me"                # optional — for notifications
#
#   Git URL (cloned fresh each run):
#     - id: external-theme
#       source: { type: git, url: https://github.com/foo/bar.git, ref: main }
#
#   Zip URL (downloaded + extracted each run):
#     - id: marketplace-theme
#       source: { type: zip, url: https://example.com/theme.zip }
#
#   Glob (auto-register all matching folders):
#     - source: { type: glob, pattern: ../themes/*, detect_woo: true }

themes: []

# Optional integrations (all opt-in):
# integrations:
#   slack:
#     webhook_url_env: SLACK_WEBHOOK_URL
#   dashboard:
#     publish: gh-pages
#     repo: myorg/theme-doctor-dashboard
`;

const GITIGNORE_CONTENT = `# Theme Doctor generated files
.theme-doctor/
goldens/
audit/
reports/
`;

export async function initWorkspace(dir: string, opts: { force: boolean }): Promise<void> {
  const configPath = path.join(dir, 'theme-doctor.yaml');

  // Bug fix: use atomic write so a crash mid-init doesn't corrupt the config
  if (!fs.existsSync(configPath) || opts.force) {
    await atomicWriteFile(configPath, DEFAULT_CONFIG);
  }

  // Write .gitignore addition
  const gitignorePath = path.join(dir, '.theme-doctor-gitignore');
  if (!fs.existsSync(gitignorePath) || opts.force) {
    await atomicWriteFile(gitignorePath, GITIGNORE_CONTENT);
  }

  // Copy default rubric files
  const defaultsExist = fs.existsSync(DEFAULTS_DIR);

  if (defaultsExist) {
    await copyDefault(
      path.join(DEFAULTS_DIR, 'rubric', 'templates.yaml'),
      path.join(dir, 'rubric', 'templates.yaml'),
      opts.force,
    );
    await copyDefault(
      path.join(DEFAULTS_DIR, 'rubric', 'flows.yaml'),
      path.join(dir, 'rubric', 'flows.yaml'),
      opts.force,
    );
    await copyDefault(
      path.join(DEFAULTS_DIR, 'blueprints', 'base.json'),
      path.join(dir, 'blueprints', 'base.json'),
      opts.force,
    );
  } else {
    // Fallback: write inline defaults
    await writeFallbackDefaults(dir, opts.force);
  }

  // Create placeholder dirs
  for (const sub of ['goldens', 'audit', 'reports', '.theme-doctor']) {
    await fsp.mkdir(path.join(dir, sub), { recursive: true });
    const keep = path.join(dir, sub, '.gitkeep');
    if (!fs.existsSync(keep)) await fsp.writeFile(keep, '');
  }
}

async function writeFallbackDefaults(dir: string, force: boolean): Promise<void> {
  const rubricDir   = path.join(dir, 'rubric');
  const blueprintDir = path.join(dir, 'blueprints');
  await fsp.mkdir(rubricDir, { recursive: true });
  await fsp.mkdir(blueprintDir, { recursive: true });

  const tplPath = path.join(rubricDir, 'templates.yaml');
  if (!fs.existsSync(tplPath) || force) {
    await atomicWriteFile(tplPath, FALLBACK_TEMPLATES_YAML);
  }

  const flowPath = path.join(rubricDir, 'flows.yaml');
  if (!fs.existsSync(flowPath) || force) {
    await atomicWriteFile(flowPath, FALLBACK_FLOWS_YAML);
  }

  const bpPath = path.join(blueprintDir, 'base.json');
  if (!fs.existsSync(bpPath) || force) {
    await atomicWriteFile(bpPath, FALLBACK_BLUEPRINT_JSON);
  }
}

const FALLBACK_TEMPLATES_YAML = `# rubric/templates.yaml
# See defaults/rubric/templates.yaml for the full built-in rubric.
# Add per-theme overrides in rubric/themes/<theme-id>.yaml

- id: home
  name: Home
  urlPattern: /
  selectors:
    - { selector: "body", required: true }

- id: shop
  name: Shop
  urlPattern: /shop/
  selectors:
    - { selector: ".woocommerce", required: true }
    - { selector: ".products", required: true }

- id: product
  name: Single Product
  urlPattern: /?p=1&post_type=product
  selectors:
    - { selector: ".single-product", required: true }
    - { selector: ".woocommerce-Price-amount", required: true }
    - { selector: ".single_add_to_cart_button", required: true }

- id: cart
  name: Cart
  urlPattern: /cart/
  selectors:
    - { selector: ".woocommerce-cart", required: true }

- id: checkout
  name: Checkout
  urlPattern: /checkout/
  selectors:
    - { selector: ".woocommerce-checkout, .wp-block-woocommerce-checkout", required: true }

- id: "404"
  name: 404
  urlPattern: /this-page-does-not-exist-td/
  selectors:
    - { selector: "body", required: true }
`;

const FALLBACK_FLOWS_YAML = `# rubric/flows.yaml
# Multi-step user journey flows.
# See defaults/rubric/flows.yaml for a complete set.

- id: purchase-flow
  name: Purchase flow (simple product)
  steps:
    - { action: navigate, url: /shop/ }
    - { action: click, selector: ".products .product a", description: "Click first product" }
    - { action: assert, selector: ".single_add_to_cart_button", description: "Add to cart button present" }
    - { action: click, selector: ".single_add_to_cart_button" }
    - { action: navigate, url: /cart/ }
    - { action: assert, selector: ".woocommerce-cart-form", description: "Cart form present" }
    - { action: screenshot, description: "Cart with item" }
`;

const FALLBACK_BLUEPRINT_JSON = JSON.stringify({
  landingPage: '/',
  preferredVersions: {
    php: '8.2',
    wp: 'latest',
  },
  phpExtensionBundles: ['kitchen-sink'],
  steps: [
    {
      step: 'login',
      username: 'admin',
      password: 'password',
    },
    {
      step: 'installPlugin',
      pluginData: {
        resource: 'wordpress.org/plugins',
        slug: 'woocommerce',
      },
    },
    {
      step: 'activatePlugin',
      pluginPath: '/wordpress/wp-content/plugins/woocommerce',
    },
    {
      step: 'runPHP',
      code: `<?php
require '/wordpress/wp-load.php';
// Create WooCommerce required pages
WC_Install::create_pages();
// Set store settings
update_option('woocommerce_store_address', '123 Main St');
update_option('woocommerce_store_city', 'San Francisco');
update_option('woocommerce_default_country', 'US:CA');
update_option('woocommerce_store_postcode', '94102');
update_option('woocommerce_currency', 'USD');
update_option('woocommerce_product_type', 'both');
update_option('woocommerce_allow_tracking', 'no');
echo 'WooCommerce configured.';
?>`,
    },
    {
      step: 'runPHP',
      code: `<?php
require '/wordpress/wp-load.php';
// Create a test simple product with fixed ID
$product = new WC_Product_Simple();
$product->set_name('Test Product');
$product->set_regular_price('29.99');
$product->set_description('A test product for Theme Doctor.');
$product->set_short_description('Test product.');
$product->set_status('publish');
$product->set_catalog_visibility('visible');
$product->set_slug('test-product');
$id = $product->save();
echo "Product created: $id";
?>`,
    },
    {
      step: 'runPHP',
      code: `<?php
require '/wordpress/wp-load.php';
// Enable debug logging
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
update_option('blogname', 'Theme Doctor Test Store');
echo 'Done.';
?>`,
    },
  ],
}, null, 2);
