import fsp from 'node:fs/promises';
import fs from 'node:fs';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type {
  ResolvedTheme,
  RunContext,
  RunJudgement,
  PatchResult,
  ThemeRunReport,
  Verdict,
} from './types.js';
import { shadowModeNote } from './safety.js';
import { formatMs } from './util.js';

const execFileAsync = promisify(execFile);

// ─── Verdict colours (ANSI) ───────────────────────────────────────────────────

const VERDICT_ICON: Record<Verdict, string> = {
  pass:       '✅',
  cosmetic:   '🎨',
  layout:     '📐',
  functional: '🚨',
};

// ─── PR creation ──────────────────────────────────────────────────────────────

export async function createPr(
  theme: ResolvedTheme,
  ctx: RunContext,
  patch: PatchResult,
  judgement: RunJudgement,
  shadowMode: boolean,
): Promise<string | undefined> {
  if (!theme.repo) {
    console.warn(`[report] No repo configured for theme "${theme.id}" — skipping PR creation.`);
    return undefined;
  }

  const branch = `theme-doctor/${ctx.runId}`;
  const failingVerdicts = judgement.verdicts.filter(v => v.verdict !== 'pass');

  const title = shadowMode
    ? `[Theme Doctor / shadow] ${failingVerdicts.length} issue(s) fixed in ${theme.id}`
    : `[Theme Doctor] ${failingVerdicts.length} issue(s) fixed in ${theme.id}`;

  const body = buildPrBody(theme, ctx, patch, judgement, shadowMode);

  try {
    // Create branch and commit in theme's local path
    const { stdout } = await execFileAsync('gh', [
      'pr', 'create',
      '--repo', theme.repo,
      '--head', branch,
      '--base', theme.branch,
      '--title', title,
      '--body', body,
      ...(shadowMode ? ['--draft'] : []),
    ], { cwd: theme.localPath });

    return stdout.trim();
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`[report] PR creation failed for "${theme.id}": ${msg}`);
    return undefined;
  }
}

function buildPrBody(
  theme: ResolvedTheme,
  ctx: RunContext,
  patch: PatchResult,
  judgement: RunJudgement,
  shadowMode: boolean,
): string {
  const lines: string[] = [
    `## Theme Doctor Report`,
    '',
    shadowMode ? `> ${shadowModeNote()}` : '',
    '',
    `**Theme:** \`${theme.id}\`  `,
    `**Run ID:** \`${ctx.runId}\`  `,
    `**Matrix:** WP ${ctx.matrix.wp} / WC ${ctx.matrix.wc} / PHP ${ctx.matrix.php}  `,
    `**Overall verdict:** ${VERDICT_ICON[judgement.overallVerdict]} ${judgement.overallVerdict}  `,
    '',
    `## Issues addressed`,
    '',
  ];

  const failing = judgement.verdicts.filter(v => v.verdict !== 'pass');
  for (const v of failing) {
    lines.push(`- ${VERDICT_ICON[v.verdict]} **${v.templateId}** @ ${v.viewport}px (${v.verdict} via ${v.tier})`);
    for (const e of v.evidence) lines.push(`  - ${e}`);
    if (v.suggestedFixHint) lines.push(`  - *Hint: ${v.suggestedFixHint}*`);
  }

  lines.push('');
  lines.push(`## Files changed`);
  lines.push('');
  for (const f of patch.filesChanged) {
    lines.push(`- \`${f}\``);
  }

  lines.push('');
  lines.push(`## Patch metadata`);
  lines.push(`- Iterations: ${patch.iterations}`);
  lines.push(`- Provenance: \`${patch.provenanceTag}\``);

  lines.push('');
  lines.push(`---`);
  lines.push(`*Generated by [Theme Doctor](https://github.com/nicholasgasior/theme-doctor)*`);

  return lines.filter(l => l !== undefined).join('\n');
}

// ─── Auto-merge gate ──────────────────────────────────────────────────────────

export function shouldAutoMerge(
  judgement: RunJudgement,
  patch: PatchResult,
  config: { autoMergeCosmetic: boolean },
): boolean {
  if (!config.autoMergeCosmetic) return false;

  // Only cosmetic verdict
  if (judgement.overallVerdict !== 'cosmetic') return false;

  // Only CSS/SCSS/asset files
  const SAFE_EXT = ['.css', '.scss', '.sass', '.less'];
  const allSafe = patch.filesChanged.every(f =>
    SAFE_EXT.includes(path.extname(f)) || f.startsWith('assets/'),
  );
  if (!allSafe) return false;

  // No functional issues remain
  const hasFunctional = judgement.verdicts.some(v => v.verdict === 'functional');
  if (hasFunctional) return false;

  return true;
}

// ─── Sparkline helper (ASCII → SVG mini chart) ───────────────────────────────

function sparklineSvg(history: Verdict[]): string {
  const W = 80; const H = 20;
  if (history.length === 0) return `<svg width="${W}" height="${H}"></svg>`;

  const SEVERITY: Record<Verdict, number> = { pass: 0, cosmetic: 1, layout: 2, functional: 3 };
  const COLOR:    Record<Verdict, string>  = {
    pass: '#22c55e', cosmetic: '#eab308', layout: '#f97316', functional: '#ef4444',
  };

  const n     = Math.min(history.length, 30);
  const items = history.slice(-n);
  const step  = W / Math.max(n - 1, 1);

  const points = items.map((v, i) => {
    const x = Math.round(i * step);
    const y = Math.round(H - (SEVERITY[v] / 3) * (H - 4) - 2);
    return `${x},${y}`;
  }).join(' ');

  const circles = items.map((v, i) => {
    const x = Math.round(i * step);
    const y = Math.round(H - (SEVERITY[v] / 3) * (H - 4) - 2);
    return `<circle cx="${x}" cy="${y}" r="2" fill="${COLOR[v]}"/>`;
  }).join('');

  return `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">
    <polyline points="${points}" fill="none" stroke="#d1d5db" stroke-width="1.5"/>
    ${circles}
  </svg>`;
}

// ─── HTML report ──────────────────────────────────────────────────────────────

export async function writeHtmlReport(
  reports: ThemeRunReport[],
  outputDir: string,
): Promise<string> {
  await fsp.mkdir(outputDir, { recursive: true });
  const indexPath = path.join(outputDir, 'index.html');

  // Group by themeId to compute history sparklines
  const historyByTheme = new Map<string, Verdict[]>();
  for (const r of reports) {
    const arr = historyByTheme.get(r.themeId) ?? [];
    arr.push(r.verdict);
    historyByTheme.set(r.themeId, arr);
  }

  const latestByTheme = new Map<string, ThemeRunReport>();
  for (const r of reports) {
    const existing = latestByTheme.get(r.themeId);
    if (!existing || r.createdAt > existing.createdAt) latestByTheme.set(r.themeId, r);
  }

  // Metrics
  const totalRuns  = reports.length;
  const passRate   = totalRuns > 0 ? Math.round((reports.filter(r => r.verdict === 'pass').length / totalRuns) * 100) : 0;
  const avgDuration = totalRuns > 0 ? Math.round(reports.reduce((s, r) => s + r.durationMs, 0) / totalRuns) : 0;
  const totalCost  = reports.reduce((s, r) => s + r.costUsd, 0);

  const cards = [...latestByTheme.values()].map(r => {
    const icon       = VERDICT_ICON[r.verdict];
    const issues     = r.judgements.filter(j => j.verdict !== 'pass').length;
    const history    = historyByTheme.get(r.themeId) ?? [r.verdict];
    const sparkline  = sparklineSvg(history);
    const matrixStr  = `WP ${r.matrix.wp} · WC ${r.matrix.wc} · PHP ${r.matrix.php}`;
    return `
    <div class="card verdict-${r.verdict}">
      <div class="card-header">
        <span class="verdict-icon">${icon}</span>
        <span class="theme-name">${r.themeId}</span>
        <span class="verdict-badge ${r.verdict}">${r.verdict}</span>
      </div>
      <div class="card-body">
        <div class="matrix">${matrixStr}</div>
        <div class="issues">${issues > 0 ? `${issues} issue${issues !== 1 ? 's' : ''}` : 'No issues'}</div>
        <div class="sparkline">${sparkline}</div>
      </div>
      <div class="card-footer">
        <span class="duration">${formatMs(r.durationMs)}</span>
        ${r.prUrl ? `<a href="${r.prUrl}" target="_blank" class="pr-link">View PR →</a>` : ''}
        <span class="run-at">${new Date(r.createdAt).toLocaleDateString()}</span>
      </div>
    </div>`;
  }).join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Theme Doctor Dashboard</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
      margin: 0; padding: 2rem; background: #f1f5f9; color: #0f172a; min-height: 100vh;
    }
    header { display: flex; align-items: center; gap: 1rem; margin-bottom: 2rem; }
    header h1 { font-size: 1.75rem; font-weight: 700; margin: 0; }
    header .subtitle { font-size: .875rem; color: #64748b; }

    .metrics {
      display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      gap: 1rem; margin-bottom: 2rem;
    }
    .metric {
      background: white; border-radius: 10px; padding: 1.25rem 1.5rem;
      box-shadow: 0 1px 3px rgba(0,0,0,.07);
    }
    .metric .value { font-size: 2rem; font-weight: 700; line-height: 1; }
    .metric .label { font-size: .75rem; color: #64748b; margin-top: .25rem; text-transform: uppercase; letter-spacing: .05em; }

    .grid {
      display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 1rem;
    }
    .card {
      background: white; border-radius: 12px; overflow: hidden;
      box-shadow: 0 1px 3px rgba(0,0,0,.08); border: 1px solid #e2e8f0;
    }
    .card.verdict-pass       { border-top: 3px solid #22c55e; }
    .card.verdict-cosmetic   { border-top: 3px solid #eab308; }
    .card.verdict-layout     { border-top: 3px solid #f97316; }
    .card.verdict-functional { border-top: 3px solid #ef4444; }

    .card-header {
      display: flex; align-items: center; gap: .5rem;
      padding: .875rem 1rem; border-bottom: 1px solid #f1f5f9;
    }
    .verdict-icon { font-size: 1.1rem; }
    .theme-name { font-weight: 600; font-size: .9rem; flex: 1; }
    .verdict-badge {
      font-size: .7rem; font-weight: 600; padding: .2em .6em;
      border-radius: 999px; text-transform: uppercase; letter-spacing: .04em;
    }
    .verdict-badge.pass       { background: #dcfce7; color: #15803d; }
    .verdict-badge.cosmetic   { background: #fef9c3; color: #854d0e; }
    .verdict-badge.layout     { background: #ffedd5; color: #9a3412; }
    .verdict-badge.functional { background: #fee2e2; color: #b91c1c; }

    .card-body { padding: .75rem 1rem; }
    .matrix  { font-size: .75rem; color: #64748b; margin-bottom: .25rem; }
    .issues  { font-size: .8rem; color: #374151; }
    .sparkline { margin-top: .5rem; }

    .card-footer {
      display: flex; align-items: center; gap: .5rem;
      padding: .6rem 1rem; background: #f8fafc; border-top: 1px solid #f1f5f9;
      font-size: .75rem; color: #94a3b8;
    }
    .pr-link { color: #2563eb; text-decoration: none; margin-left: auto; }
    .pr-link:hover { text-decoration: underline; }
    .run-at { margin-left: auto; }
    .pr-link + .run-at { margin-left: 0; }

    footer { margin-top: 2rem; font-size: .75rem; color: #94a3b8; text-align: center; }

    @media (prefers-color-scheme: dark) {
      body { background: #0f172a; color: #f1f5f9; }
      .card, .metric { background: #1e293b; border-color: #334155; }
      .card-header, .card-body, .card-footer { border-color: #334155; }
      .card-footer { background: #1e293b; }
    }
  </style>
</head>
<body>
  <header>
    <div>
      <h1>🩺 Theme Doctor</h1>
      <div class="subtitle">Generated ${new Date().toLocaleString()}</div>
    </div>
  </header>

  <div class="metrics">
    <div class="metric">
      <div class="value">${latestByTheme.size}</div>
      <div class="label">Themes</div>
    </div>
    <div class="metric">
      <div class="value">${passRate}%</div>
      <div class="label">Pass rate</div>
    </div>
    <div class="metric">
      <div class="value">${totalRuns}</div>
      <div class="label">Total runs</div>
    </div>
    <div class="metric">
      <div class="value">${formatMs(avgDuration)}</div>
      <div class="label">Avg duration</div>
    </div>
    <div class="metric">
      <div class="value">$${totalCost.toFixed(2)}</div>
      <div class="label">Total AI cost</div>
    </div>
  </div>

  <div class="grid">
    ${cards || '<p style="color:#94a3b8">No runs yet. Run <code>theme-doctor run</code> to get started.</p>'}
  </div>

  <footer>
    <a href="https://github.com/nicholasgasior/theme-doctor" style="color:#94a3b8">Theme Doctor</a>
    &nbsp;·&nbsp; MIT License
  </footer>
</body>
</html>`;

  await fsp.writeFile(indexPath, html);
  return indexPath;
}

// ─── Dashboard JSON ───────────────────────────────────────────────────────────

export async function writeDashboardJson(
  reports: ThemeRunReport[],
  outputDir: string,
): Promise<string> {
  await fsp.mkdir(outputDir, { recursive: true });
  const jsonPath = path.join(outputDir, 'dashboard.json');
  await fsp.writeFile(jsonPath, JSON.stringify({ generatedAt: new Date().toISOString(), reports }, null, 2));
  return jsonPath;
}

// ─── Static dashboard builder ─────────────────────────────────────────────────

export async function buildDashboard(configDir: string): Promise<string> {
  const reportsDir  = path.join(configDir, 'reports');
  const dashDir     = path.join(reportsDir, 'dashboard');
  const allReports: ThemeRunReport[] = [];

  if (fs.existsSync(reportsDir)) {
    const runDirs = await fsp.readdir(reportsDir);
    for (const runId of runDirs) {
      if (runId === 'dashboard') continue;
      const reportPath = path.join(reportsDir, runId, 'report.json');
      if (fs.existsSync(reportPath)) {
        const data = JSON.parse(await fsp.readFile(reportPath, 'utf8'));
        if (Array.isArray(data)) allReports.push(...data);
        else allReports.push(data as ThemeRunReport);
      }
    }
  }

  await writeHtmlReport(allReports, dashDir);
  await writeDashboardJson(allReports, dashDir);
  return path.join(dashDir, 'index.html');
}

// ─── Slack notification ───────────────────────────────────────────────────────

export async function notifySlack(
  webhookUrl: string,
  reports: ThemeRunReport[],
): Promise<void> {
  const failing = reports.filter(r => r.verdict !== 'pass');
  if (failing.length === 0) return;

  const text = [
    `🩺 *Theme Doctor* found ${failing.length} issue(s):`,
    ...failing.map(r => `• ${VERDICT_ICON[r.verdict]} ${r.themeId}: ${r.verdict} (${r.judgements.filter(j => j.verdict !== 'pass').length} templates)`),
  ].join('\n');

  const got = await import('got');
  await got.default.post(webhookUrl, { json: { text } });
}
